### ISSUE TITLE
Compile to Native

### ISSUE THREAD

**Issue by Laxystem** [chRyNaN/colors#2]
**Is your feature request related to a problem? Please describe.**
Yes, I would like to use this library - but it is simply unavailable on Native.
![image](https://github.com/chRyNaN/colors/assets/127752744/abe35fd5-9c0d-465d-b59a-08ec43114aa3)

**Describe the solution you'd like**
Compile colors to Kotlin Native.

**Describe alternatives you've considered**
I would create my own library.

**Additional context**
Your GitHub issue form is broken.

**Comment by Laxystem** [comment]
Any info, please? Very important to me.

**Comment by chRyNaN** [comment]
Fixed with release 1.0.0 https://github.com/chRyNaN/colors/releases/tag/1.0.0
